services:
  likelion-db:
    image: mysql:8.0.41
    container_name: likelion-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 974300
      MYSQL_DATABASE: likelion
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - 3305:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping" ]
      interval: 3s
      retries: 10

  redis-server:
    image: redis
    ports:
      - 6379:6379