name: Deploy To EC2
on:
  push:
    branches:
      - Setting/#11

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository에 올린 파일들을 불러오기
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACTION_TOKEN }}
          submodules: true

      - name: JDK 21버전 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: 빌드하기
        run: ./gradlew clean build -x test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/likelion:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/likelion:latest

      - name: Aws 배포
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          script_stop: true
          script: |
            docker stop likelion || true
            docker rm -f likelion || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/likelion:latest
            docker run -d --name likelion -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/likelion:latest